version: '3'

volumes:
  db_data: {}

services:
  db:
    image: mongo
    container_name: 'mongo-container'
    ports:
      - '27017:27017'

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
