development:
  clients:
    default:
      database: e_commerce_development
      hosts:
        - db:27017
test:
  clients:
    default:
      database: e_commerce_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
