development:
  clients:
    default:
      database: <%= ENV['MONGO_DB'] %>
      hosts:
        - <%= ENV['DATABASE_HOST'] %>:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: e_commerce_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
